language: java
jdk:
  - openjdk8

branches:
  only:
    - master

before_install:
  - chmod +x gradlew

# Travis CI 서버의 Home.
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

before_deploy:
  - mkdir -p before-deploy # zip에 포함시킬 파일들을 담을 디렉토리 생성
  - cp scripts/*.sh before-deploy/
  - cp appspec.yml before-deploy/
  - cp build/libs/*.jar before-deploy/
  - cd before-deploy && zip -r before-deploy * # before-deploy로 이동후 전체 압축
  - cd ../ && mkdir -p deploy # 상위 디렉토리로 이동후 deploy 디렉토리 생성
  - mv before-deploy/before-deploy.zip deploy/attendance-management-service.zip # deploy로 zip파일 이동

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY      #The value that was set on Travis repository
    secret_access_key: $AWS_SECRET_KEY  #The value that was set on Travis repository
    bucket: org-sarang-attendance-build #AWS S3's bucket name
    region: ap-northeast-2
    skip_cleanup: true
    acl: private                        #Make access license about Zip file to private
    local_dir: deploy                   #The directory that was created in before_deploy
    wait-until-deployed: true

  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: org-sarang-attendance-build
    key: attendance-management-service.zip
    bundle_type: zip
    application: attendance-management-service
    deployment_group: attendance-management-service-group
    region: ap-northeast-2
    wait-until-deployed: true

# Notify with email at Complete running TEST
notifications:
  email:
    recipients:
      rlaalfks@gmail.com
