language: java
jdk:
  - openjdk8

branches:
  only:
    - master

before_install:
  - chmod +x gradlew

# Home of Travis CI Server
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

before_deploy:
  - zip -r attendance-management-service *  #Project name (file name)
  - mkdir -p deploy
  - mv attendance-management-service.zip deploy/attendance-management-service.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY      #The value that was set on Travis repository
    secret_access_key: $AWS_SECRET_KEY  #The value that was set on Travis repository
    bucket: attendance-management-build #AWS S3's bucket name
    region: ap-northeast-2
    skip_cleanup: true
    acl: private                        #Make access license about Zip file to private
    local_dir: deploy                   #The directory that was created in before_deploy
    wait-until-deployed: true
    
  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: attendance-management-build
    key: attendance-management-service.zip  #Transfer the build file after compressing
    bundle_type: zip
    application: attendance-management-service  #The application that was registered  in AWS web console.
    deployment_group: attendance-management-service-group #The CodeDeploy's deployment group that was registered int AWS web console
    region: ap-northeast-2
    wait-until-deployed: true



# Notify with email at Complete running
notifications:
  email:
    recipients:
      rlaalfks@gmail.com
