language: java
jdk:
  - openjdk8

branches:
  only:
    - master

before_install:
  -chmod +x gradlew

# Home of Travis CI Server
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

# Notify with email at Complete running
notifications:
  email:
    recipients:
      rlaalfks@gmail.com
