version: 0.0
os: linux
files:
  - source:  /
    destination: /home/ec2-user/app/step3/zip/
    overwrite: yes

permissions:
  - object:  /
    pattern: "**"
    owner: ec2-user
    group: ec2-user

hooks:
  AfterInstall:
    - location: stop.sh   #Shut down the spring boot that is not connected with nginx
      timeout: 60
      runas: ec2-user
  ApplicationStart:
    - location: start.sh  #Start the new version of spring boot with port that is not connected with nginx
      timeout: 60
      runas: ec2-user
  ValidateService:
    - location: health.sh #Confirm execution of a new version of spring boot correctly
      timeout: 60
      runas: ec2-user